#!/usr/bin/env python3

"""Auto-generate lineage model configurations."""

import re
from pathlib import Path
from typing import Final

from rich import print as rprint
from typer import Typer

from speclet.io import lineage_modeling_data_dir
from speclet.project_configuration import get_model_configuration_file

app = Typer()


TEMPLATE_CONFIG: Final[
    str
] = """
- name: hnb-single-lineage-{{LINEAGE}}
  description: "
    Single lineage hierarchical negative binomial model for {{LINEAGE}} data.
  "
  active: true
  model: LINEAGE_HIERARCHICAL_NB
  data_file: "modeling_data/lineage-modeling-data/depmap-modeling-data_{{LINEAGE}}.csv"
  model_kwargs:
    lineage: "{{LINEAGE}}"
    min_n_cancer_genes: 3
    min_frac_cancer_genes: 0.2
  sampling_kwargs:
    pymc_numpyro:
      draws: 1000
      tune: 2000
      target_accept: 0.99
      idata_kwargs:
        log_likelihood: false
      nuts_kwargs:
        step_size: 0.01
  slurm_resources:
    PYMC_NUMPYRO:
      mem: 32
      time: 8
      cores: 1
      gpu:
        gpu: "RTX 8000"
"""


def _make_config(lineage: str) -> str:
    return TEMPLATE_CONFIG.replace("{{LINEAGE}}", lineage)


def _list_lineages() -> list[str]:
    lineage_files = [f for f in lineage_modeling_data_dir().iterdir()]
    lineage_files = [f for f in lineage_files if "depmap-modeling-data" in f.name]
    pattern = r"(?<=depmap-modeling-data_).*(?=\.csv)"
    lineages: list[str] = [re.findall(pattern, f.name)[0] for f in lineage_files]
    lineages.sort()
    rprint(f"Found {len(lineages)} lineages.")
    return lineages


def _insert_lineage_configs(config_file: Path, new_text: str) -> None:
    START = "## >>> AUTO GEN LINEAGES >>>\n"
    END = "## <<<\n"
    with open(config_file, "r") as file:
        config_lines = list(file)

    start_i = config_lines.index(START)
    end_i = config_lines.index(END)

    new_config_lines: list[str] = config_lines[: (start_i + 1)]
    new_config_lines += [new_text, "\n"]
    new_config_lines += config_lines[end_i:]
    new_config = "".join(new_config_lines)

    rprint(f"Updating new configuration file '{config_file}'.")
    rprint(f"Changes made between lines {start_i+1}-{end_i+1}.")
    with open(config_file, "w") as file:
        file.write(new_config)
    return None


@app.command()
def insert(config: Path | None = None) -> None:
    """Autogenerate model configurations for all cell line lineages.

    Inserts model configurations for all lineages with data in the specific folder for
    lineage modeling data files.

    Inserts the configurations between '## >>> AUTO GEN LINEAGES >>>\n' and '## <<<\n'.

    Args:
        config (Path | None, optional): Model configuration file. Defaults to `None`
        which results in using the default configuration in the project configuration.
    """
    rprint("[blue]Autogenerate cell line lineage configurations.[/blue]")
    if config is None:
        config = get_model_configuration_file()

    lineage_configs = "\n".join([_make_config(line) for line in _list_lineages()])
    _insert_lineage_configs(config, lineage_configs)
    rprint("Done! :party_popper:")
    return None


@app.command()
def clear(config: Path | None = None) -> None:
    """Clear autogenerated model configurations for cell line lineages.

    Clears the text in the configuration file between
    '## >>> AUTO GEN LINEAGES >>>\n' and '## <<<\n'.

    Args:
        config (Path | None, optional): Model configuration file. Defaults to `None`
        which results in using the default configuration in the project configuration.
    """
    rprint("[blue]Clearing cell line lineage configurations.[/blue]")
    if config is None:
        config = get_model_configuration_file()

    _insert_lineage_configs(config, "\n")
    rprint("Done! :ok_hand:")
    return None


if __name__ == "__main__":
    app()
