# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >
    (?x)^(
    renv/library/.*|
    docs/.*
    )$
repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        args: [--fix]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, main]
    -   id: trailing-whitespace
        exclude: "presentations/"
    -   id: end-of-file-fixer
        exclude: "presentations/"
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=80000"]
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    - id: shellcheck
-   repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
    - id: isort
      types: [python]
      args: [--line-length=100, --profile=black]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        exclude: ".snakemake."
        additional_dependencies: [pydantic]
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        exclude: ".snakemake."
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        types: [python]
        exclude: ".snakemake."
        files: "src/.*"
        args: [--convention=google, --add-ignore=D301]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        types: [python]
        exclude: ".snakemake."
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: "renv/library/.*"
    -   id: parsable-R
    -   id: no-browser-statement
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.13.1
    hooks:
    -   id: nbqa-isort
        args: [--nbqa-mutate, --line-length=100, --profile=black]
        exclude: "munge/019_prepare-data-subsample.ipynb"
    -   id: nbqa-black
        args: [--nbqa-mutate]
        exclude: "munge/019_prepare-data-subsample.ipynb"
    -   id: nbqa-pyupgrade
        args: [--nbqa-mutate]
        exclude: "munge/019_prepare-data-subsample.ipynb"
    -   id: nbqa-mypy
        args: [--nbqa-mutate]
        additional_dependencies: [pydantic, mypy]
        types: [jupyter]
        exclude: "munge/019_prepare-data-subsample.ipynb"
