# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        exclude: ".snakemake."
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: parsable-R
    -   id: no-browser-statement
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.4.1
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==20.8b1]
        args: [--nbqa-mutate]
        exclude: "munge/019_prepare-data-subsample.ipynb"
    -   id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
        args: [--nbqa-mutate]
        exclude: "munge/019_prepare-data-subsample.ipynb"
    -   id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
        args: [--nbqa-mutate]
        exclude: "munge/019_prepare-data-subsample.ipynb"
