name: speclet
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.1
  - arviz=0.11.1
  - black=20.8b1
  - colorama=0.4.4
  - graphviz=2.42.3
  - ipykernel=5.4.2
  - ipython=7.20.0
  - isort=5.7.0
  - jupyter-lsp=1.1.3
  - jupyterlab=3.0.7
  - jupyterlab-git=0.22.0
  - jupyterlab_code_formatter=1.4.4
  - matplotlib=3.3.4
  - mkl=2020.4
  - mypy=0.800
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nbqa=0.5.7
  - nodejs=14.15.1
  - numpy=1.20.1
  - pandas=1.2.2
  - patsy=0.5.1
  - pillow=8.1.0
  - pip=21.0.1
  - plotnine=0.7.1
  - pre-commit=2.10.1
  - pretty_errors=1.2.19
  - pymc3=3.11.1
  - requests=2.25.1
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - theano=1.0.5
  - theano-pymc=1.1.2
  - virtualenv=20.4.2
  - watermark=2.1.0
  - pytest=6.2.2
  - pip:
    - asttokens==2.0.4
    - executing==0.5.4
    - icecream==2.1.0
