name: speclet
channels:
  - conda-forge
  - nvidia
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.10.5
  - aeppl
  - aesara
  - arviz>=0.12.0
  - black
  - colorama
  - coverage
  - dask
  - factory_boy
  - faker
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - hypothesis
  - ipython
  - ipywidgets
  - isort
  - jax>=0.3.0
  - jaxlib>=0.3.0
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker
  - mamba
  - matplotlib>=3.5.0
  - mypy
  - nbconvert
  - nbformat
  - nbqa
  - nbterm
  - numpy>=1.22.0
  - numpyro>=0.9.0
  - pandas>=1.3.0
  - pandera>=0.8.0
  - pandoc
  - papermill
  - patsy
  - pip
  - plotnine
  - pdoc3
  - pre-commit
  - pretty_errors
  - pydantic
  - pyjanitor
  - pymc>=4.1.0
  - pytest
  - pytest-cov
  - pytest-sugar
  - python-graphviz
  - requests
  - rich
  - scikit-learn>=1.0.0
  - scikit-misc
  - seaborn
  - statsmodels
  - termcolor
  - typer
  - types-pyyaml
  - watermark
  - xarray>=2022.3.0
  - pip:
    - pytest-pythonpath
    - python-dotenv
    - types-python-dateutil
    - -e .  # install the source directory as a package (keep as last)
