name: speclet_smk
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.10.*
  - snakemake=7.3.*
  - arviz>=0.12.0
  - black  # KEEP! used in pipeline
  - blas  # may be able to remove in next PyMC beta release
  - colorama
  - dask
  - drmaa
  - ipywidgets
  - isort  # KEEP! used in pipeline
  - jax>=0.3.0
  - jaxlib>=0.3.0
  - jupyterlab
  - mamba
  - nbconvert
  - nbqa  # KEEP! used in pipeline
  - numpy
  - numpyro
  - pandas
  - pandera
  - papermill
  - pip
  - plotnine
  - pretty_errors
  - pydantic
  - pyjanitor
  - pymc>=4.0.0b5
  - python-graphviz
  - rich
  - scikit-learn>=1.0.0
  - scikit-misc
  - seaborn
  - statsmodels
  - typer
  - watermark
  - pip:
    - python-dotenv
    - -e .  # install the source directory as a package (keep as last)
