name: speclet-test
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.6
  - jupyterlab=3.1.*
  - pymc3=3.11.2
  - altair=4.1.*
  - arviz=0.11.2
  - black
  - colorama=0.4.*
  - coverage=5.5
  - factory_boy=3.2.0
  - faker=8.11.0
  - flake8=3.9.*
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - graphviz=2.48.*
  - hypothesis=6.14.8
  - ipython=7.26.*
  - isort=5.9.*
  - jedi
  - jupyterlab_code_formatter
  - matplotlib=3.4.*
  - mkl=2021.3.*
  - mypy=0.910
  - nbconvert=6.1.*
  - nbdime
  - nbformat=5.1.*
  - nbqa=1.1.*
  - nodejs
  - numpy=1.21.2
  - openssl
  - pandas=1.3.2
  - pandoc=2.14.*
  - papermill=2.3.*
  - patsy=0.5.*
  - pip=21.2.*
  - plotnine=0.8.*
  - pdoc3
  - pre-commit=2.14.*
  - pretty_errors=1.2.*
  - pydantic=1.8.*
  - pyjanitor=0.21.0
  - pytest=6.2.*
  - pytest-cov
  - pytest-sugar
  - python-graphviz=0.17
  - requests=2.26.*
  - rich=10.7.*
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.*
  - statsmodels=0.12.2
  - termcolor=1.1.*
  - theano=1.0.5
  - theano-pymc=1.1.2
  - typer=0.3.*
  - types-pyyaml
  - watermark
  - xarray=0.19.0
  - pip:
    - pytest-pythonpath
    - pytest-testmon
    - pytest-watch
    - types-python-dateutil
    - -e .  # install the source directory as a package (keep as last)
