name: speclet_smk
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.9
  - snakemake=7.3.*
  - arviz>=0.11.0
  - black  # KEEP! used in pipeline
  - colorama
  - dask
  - drmaa
  # - gcc  # not needed on macOS
  # - gxx  # not needed on macOS
  - isort  # KEEP! used in pipeline
  - jupyterlab
  - mamba
  - nbconvert
  - nbqa  # KEEP! used in pipeline
  - numpy
  - pandas
  - pandera
  - papermill
  - pip
  - plotnine
  - pretty_errors
  - pydantic
  - pyjanitor
  - python-graphviz
  - rich
  - scikit-learn>=1.0.0
  - scikit-misc
  - seaborn
  - statsmodels
  - typer
  - watermark
  - aeppl=0.0.27
  - aesara=2.5.1
  - blas
  - cachetools>=4.2.1
  - cloudpickle
  - fastprogress>=0.2.0
  - h5py>=2.7
  - jax
  - jaxlib>=0.3.0
  - libblas=*=*mkl
  - mkl-service
  - scipy>=1.4.1
  - typing-extensions>=3.7.4
  - ipython>=7.16
  - pip:
    - polyagamma
    - pystan==3.1.1  # latest version for O2
    - python-dotenv
    - git+https://github.com/pymc-devs/pymc.git
    - -e .  # install the source directory as a package (keep as last)
