name: speclet
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.2
  - jupyterlab=3.0.10
  - pymc3=3.11.1
  - altair-4.1.0
  - arviz=0.11.2
  - black=20.8b1
  - colorama=0.4.4
  - coverage=5.5
  - flake8=3.9.0
  - flake8-bugbear=21.4.3
  - flake8-builtins=1.5.3
  - flake8-comprehensions=3.4.0
  - graphviz=2.47.0
  - hypothesis=6.13.14
  - ipython=7.21.0
  - isort=5.7.0
  - jedi=0.18.0
  - jupyterlab_code_formatter=1.4.4
  - matplotlib=3.3.4
  - mkl=2020.4
  - mypy=0.812
  - nbconvert=6.0.7
  - nbdime=2.1.0
  - nbformat=5.1.2
  - nbqa=0.5.9
  - nodejs
  - numpy=1.20.1
  - openssl=1.1.1k
  - pandas=1.2.3
  - pandoc=2.12
  - papermill=2.3.3
  - patsy=0.5.1
  - pip=21.0.1
  - plotnine=0.7.1
  - pdoc3=0.8.1
  - pre-commit=2.11.1
  - pretty_errors=1.2.19
  - pydantic=1.8.1
  - pytest=6.2.2
  - pytest-cov=2.11.1
  - pytest-sugar=0.9.4
  - python-graphviz=0.16
  - pyjanitor=0.20.14
  - requests=2.25.1
  - rich=10.1.0
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - statsmodels=0.12.2
  - termcolor=1.1.0
  - theano=1.0.5
  - theano-pymc=1.1.2
  - typer=0.3.2
  - types-pyyaml=5.4.3
  - watermark=2.2.0
  - xarray=0.18.0
  - pip:
    - pytest-pythonpath==0.7.3
    - pytest-testmon==1.1.1
    - pytest-watch==4.2.0
    - -e .  # install the source directory as a package (keep as last)
