# Configurations used throughout the project.

munge:
  test: True
  temporary_directory: "temp"

modeling:
  highest_density_interval: 0.89
  models_config: "model-configs.yaml"

fitting_pipeline:
  debug: True
