# Configurations used throughout the project.

munge:
  test: false
  temporary_directory: "temp"

modeling:
  highest_density_interval: 0.89
  models_config: "models/model-configs.yaml"

fitting_pipeline:
  debug: false
  num_chains: 3
  models_config: "models/model-configs.yaml"
  temp_dir: "temp/fitting-mcmc"
  model_cache_dir: "models/"
  reports_dir: "reports/model-fitting-pipeline-reports/"
  benchmark_dir: "benchmarks/010_010_model-fitting-pipeline"
  env_yaml: "default_environment.yaml"

# misc:
#   aesara_gcc_flag: 'cxx="$CONDA_PREFIX/bin/g++",blas__ldflags="-L$CONDA_PREFIX/lib -lopenblas -lopenblas -Wl,-rpath,$CONDA_PREFIX/lib"'
