name: speclet_snakemake
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.*
  - snakemake=6.5.*
  - colorama=0.4.*
  - drmaa=0.7.*
  - future=0.18.*
  - graphviz=2.47.*
  - ipython=7.25.*
  - nbconvert=6.1.*
  - networkx=2.6.*
  - numpy=1.21.*
  - openssl=1.1.*
  - pandas=1.3.*
  - papermill=2.3.*
  - pip=21.1.*
  - pretty_errors=1.2.*
  - pydantic=1.8.*
  - pytest=6.2.*
  - watermark=2.2.*
  - pip:
    - -e .  # install the source directory as a package (keep as last)
