name: speclet_snakemake
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.6
  - snakemake=6.7.*
  - colorama=0.4.*
  - dask=2021.10.*
  - drmaa=0.7.*
  - future=0.18.*
  - graphviz=2.48.*
  - ipython=7.26.*
  - jupyterlab=3.1.*
  - mamba=0.15.*
  - mkl=2021.3.*
  - mkl-service=2.4.*
  - nbconvert=6.1.*
  - networkx
  - numpy=1.21.*
  - openssl
  - pandas=1.3.*
  - papermill=2.3.*
  - pip=21.2.*
  - plotnine=0.8.*
  - pretty_errors=1.2.*
  - pydantic=1.8.*
  - pyjanitor=0.21.*
  - pymc3=3.11.*
  - pytest=6.2.*
  - rich=10.12.*
  - seaborn=0.11.*
  - theano=1.0.5
  - theano-pymc=1.1.2
  - typer=0.4.*
  - watermark
  - pip:
    - -e .  # install the source directory as a package (keep as last)
