name: speclet_snakemake
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.8.8
  - snakemake=5.32.2
  - colorama
  - drmaa=0.7.9
  - graphviz
  - networkx
  - numpy=1.20.1
  - pandas=1.2.3
  - openssl
  - pip
  - pretty_errors
  - pytest
  - papermill=2.3.3
  - pydantic=1.8.1
  - pip:
    - -e .  # install the source directory as a package (keep as last)
