name: speclet_smakemake
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - colorama
  - drmaa=0.7.9
  - graphviz
  - networkx
  - numpy
  - pandas
  - openssl
  - pip
  - pretty_errors
  - pytest
  - papermill
  - python=3.8.8
  - snakemake=5.32.2
