__default__:
  partition: "short"
  cores: 1
  mem: "1000"
  time: "00:10:00"
  out: "logs/%j_{rule}.log"
  err: "logs/%j_{rule}.log"
  mail: "NONE"
  J: "snakejob"
sample_mcmc:
  partition: "{params.partition}"
  cores: 1
  mem: "{params.mem}"
  time: "{params.time}"
  J: "mcmc"
combine_mcmc":
  partition: "short"
  cores: 1
  mem: "32000"
  time: "00:15:00"
  J: "combine"
sample_advi:
  partition: "{params.partition}"
  cores: 1
  mem: "{params.mem}"
  time: "{params.time}"
  J: "advi"
papermill_report:
  partition: "short"
  cores: 1
  mem: "100"
  time: "00:01:00"
  J: "papermill"
execute_report:
  partition: "short"
  cores: 1
  mem: "100000"
  time: "01:30:00"
  J: "report"
