name: speclet
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - arviz=0.11.2
  - autopep8
  - black
  - bleach
  - click
  - colorama
  - coverage
  - graphviz
  - ipython
  - isort
  - jedi
  - jupyterlab=3.0.10
  - jupyterlab-git
  - jupyterlab_code_formatter
  - matplotlib
  - mkl
  - mypy
  - nbconvert
  - nbdime
  - nbformat
  - nbqa
  - nodejs
  - numpy
  - openssl
  - pandas
  - pandoc
  - papermill
  - patsy
  - pip
  - plotnine
  - pre-commit
  - pretty_errors
  - pydantic
  - pymc3=3.11.1
  - pytest
  - pytest-cov
  - pytest-sugar
  - python=3.9.2
  - python-graphviz
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - termcolor
  - theano
  - theano-pymc
  - typer
  - watermark
  - pip:
    - pytest-pythonpath
    - -e /n/data2/dfci/cancerbio/haigis/Cook/speclet/  # install the source directory as a package (keep as last)
