__default__:
  partition: "short"
  cores: 1
  mem: "1000"
  time: "00:10:00"
  out: "logs/%j_{rule}.log"
  err: "logs/%j_{rule}.log"
  mail: "NONE"
  J: "snakejob"
sample_pymc_mcmc:
  partition: "{params.partition}"
  cores: 1
  mem: "{params.mem}"
  time: "{params.time}"
  J: "pymc-mc"
combine_pymc_mcmc:
  partition: "short"
  cores: 1
  mem: "32000"
  time: "01:00:00"
  J: "pymc-comb"
sample_pymc_numpyro:
  partition: "{params.partition}"
  cores: 1
  mem: "{params.mem}"
  time: "{params.time}"
  J: "pyro-mc"
combine_pymc_numpyro:
  partition: "short"
  cores: 1
  mem: "32000"
  time: "01:00:00"
  J: "pyro-comb"
sample_pymc_advi:
  partition: "{params.partition}"
  cores: 1
  mem: "{params.mem}"
  time: "{params.time}"
  J: "pymc-advi"
summarize_posterior:
  partition: "short"
  cores: 2
  mem: "16000"
  time: "00:30:00"
  J: "summary"
execute_report:
  partition: "medium"
  cores: 1
  mem: "200000"
  time: "30:00:00"
  J: "report"
