name: speclet-pipeline-env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.9
  - jupyterlab
  - pymc3=3.11.*
  - arviz
  - colorama
  - dask
  - ipython
  - matplotlib
  - mkl
  - mkl-service
  - nbconvert
  - numpy
  - pandas
  - pandoc
  - papermill
  - patsy
  - pip
  - plotnine
  - pretty_errors
  - pydantic
  - pyjanitor
  - python-graphviz
  - requests
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - termcolor
  - theano-pymc=1.1.*
  - typer
  - watermark
  - xarray
  - pip:
    - pystan>=3.3.0
    - -e .  # install the source directory as a package (keep as last)
