name: speclet-pipeline-env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.9
  - arviz>=0.11.0
  - black
  - colorama
  - coverage
  - dask
  - factory_boy
  - faker
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - hypothesis
  - ipython
  - isort
  - jupyterlab=3.2.*
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker
  - mamba
  - matplotlib>=3.5.0
  - mypy
  - nbconvert
  - nbformat
  - nbqa
  - numpy>=1.22.0
  - pandas>=1.3.0
  - pandera>=0.8.0
  - pandoc
  - papermill
  - patsy
  - pip
  - plotnine
  - pdoc3
  - pre-commit
  - pretty_errors
  - pydantic
  - pyjanitor
  - pytest
  - pytest-cov
  - pytest-sugar
  - python-graphviz
  - requests
  - rich
  - scikit-learn>=1.0.0
  - scikit-misc
  - seaborn
  - statsmodels
  - termcolor
  - typer
  - types-pyyaml
  - watermark
  - xarray=0.20.*
  - aeppl=0.0.26
  - aesara=2.3.8
  - blas
  - cachetools>=4.2.1
  - cloudpickle
  - fastprogress>=0.2.0
  - h5py>=2.7
  - ipython>=7.16
  - myst-nb
  - scipy>=1.4.1,<1.8.0
  - typing-extensions>=3.7.4
  - pip:
    - polyagamma
    - pystan==3.1.1  # latest version for O2
    - pytest-pythonpath
    - pytest-testmon
    - pytest-watch
    - python-dotenv
    - types-python-dateutil
    - git+https://github.com/pymc-devs/pymc.git
    - -e .  # install the source directory as a package (keep as last)
