name: speclet-pipeline-env
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.6
  - jupyterlab=3.1.7
  - pymc3=3.11.2
  - arviz=0.11.2
  - black=21.7b0
  - colorama=0.4.4
  - coverage=5.5
  - graphviz=2.48.0
  - ipython=7.26.0
  - isort=5.9.3
  - jedi=0.18.0
  - matplotlib=3.4.3
  - mkl=2021.3.0
  - mkl-service=2.4.*
  - mypy=0.910
  - nbconvert=6.1.0
  - nbqa=1.1.0
  - numpy=1.21.2
  - openssl=1.1.1k
  - pandas=1.3.2
  - pandoc=2.14.1
  - papermill=2.3.3
  - patsy=0.5.1
  - pip=21.2.4
  - plotnine=0.8.0
  - pretty_errors=1.2.23
  - pydantic=1.8.2
  - pyjanitor=0.21.0
  - python-graphviz=0.17
  - requests=2.26.0
  - rich=10.7.0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - statsmodels=0.12.2
  - termcolor=1.1.0
  - theano=1.0.5
  - theano-pymc=1.1.2
  - typer=0.3.2
  - watermark=2.2.0
  - xarray=0.19.0
  - pip:
    - pytest-pythonpath==0.7.3
    - -e /n/data1/hms/dbmi/park/Cook/speclet/  # install the source directory as a package (keep as last)
