# Model configurations for pipelines.

configurations:
  - name: SpecletSeven-debug
    model: speclet-seven
    fit_method: MCMC
  - name: SpecletSeven-debug
    model: speclet-seven
    fit_method: ADVI
