name: speclet_smakemake
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.2
  - black=20.8b1
  - ipython=7.21.0
  - isort=5.7.0
  - jupyterlab=3.0.10
  - matplotlib=3.3.4
  - nbconvert=6.0.7
  - nbqa=0.5.9
  - nbformat=5.1.2
  - numpy=1.20.1
  - pandas=1.2.3
  - pyjanitor=0.20.14
  - pandoc=2.12
  - plotnine=0.7.1
  - seaborn=0.11.1
