name: munge
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.9
  - jupyterlab
  - black
  - colorama
  - dask=2022.3.*
  - ipython
  - isort
  - jedi
  - matplotlib=3.*
  - nbconvert
  - nbdime
  - nbformat
  - nbqa
  - numpy=1.22.*
  - pandas=1.3.*
  - pandoc
  - papermill
  - plotnine
  - pretty_errors
  - pydantic
  - python-graphviz
  - pyjanitor
  - rich
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - typer
  - watermark
