on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: pytest
jobs:
  pytest:
    name: pytest suite
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda environment
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: speclet
          auto-activate-base: false
          channel-priority: strict
          environment-file: environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Activate conda environment
        shell: bash -l {0}
        run: conda activate speclet
      - name: Describe virtual environment
        shell: bash -l {0}
        run: |
          python3 --version
          which python3
          conda env list
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          python3 -m pytest \
            --disable-warnings \
            --cov="src" \
            --force-sugar \
            tests/
