# Run test suite.

name: "pytest"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: "pytest suite"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Install conda"
        uses: conda-incubator/setup-miniconda@v2

      - name: "Create and setup conda environment"
        shell: bash -l {0}
        run: |
          conda install -n base -c conda-forge mamba
          mamba env create -f conda.yaml
          conda activate speclet

      - name: "Describe environment"
        shell: bash -l {0}
        run: |
          pwd
          ls -lha
          python3 --version
          which python3
          conda env list
          conda list

      - name: "Run test suite"
        shell: bash -l {0}
        run: |
          python3 -m pytest \
            --disable-warnings \
            --force-sugar \
            tests
