on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
name: pytest
jobs:
  pytest:
    name: pytest suite
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: speclet
          auto-activate-base: false
          channel-priority: strict
          environment-file: environment.yml
      - name: Activate conda environment
        shell: bash -l {0}
        run: conda activate speclet
      - name: Describe virtual environment
        shell: bash -l {0}
        run: |
          python3 --version
          which python3
          conda env list
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          python3 -m pytest \
            --disable-warnings \
            --cov="src" \
            --force-sugar \
            tests/
