name: "project-build"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * MON'
  push:
    branches:
      - master
      - gh-action-ci

defaults:
  run:
    shell: bash -l {0}

jobs:
  snakemake:
    name: "Snakemake pipelines"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Install conda"
        uses: conda-incubator/setup-miniconda@v2

      - name: "Create and setup conda environment"
        run: |
          conda install -n base --yes -c conda-forge mamba
          mamba env create -f conda_smk.yaml
          conda activate speclet_smk

      - name: "Describe environment"
        run: |
          conda activate speclet_smk
          pwd
          ls -lha
          python3 --version
          which python3
          conda env list
          conda list

      - name: "Data download pipeline"
        run: |
          conda activate speclet_smk
          snakemake \
            --snakefile data/download-data.smk \
            --dry-run \
            --forceall

      - name: "Data preparation pipeline"
        run: |
          conda activate speclet_smk
          snakemake \
            --snakefile munge/munge.smk \
            --dry-run \
            --forceall

      - name: "Model fitting pipeline"
        run: |
          conda activate speclet_smk
          snakemake \
            --snakefile pipelines/010_010_model-fitting-pipeline.smk \
            --dry-run \
            --forceall

  model-config-check:
    name: "Model configurations"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "Install conda"
        uses: conda-incubator/setup-miniconda@v2

      - name: "Create and setup conda environment"
        run: |
          conda install -n base --yes -c conda-forge mamba
          mamba env create -f conda.yaml
          conda activate speclet

      - name: "Describe environment"
        run: |
          conda activate speclet
          pwd
          ls -lha
          python3 --version
          which python3
          conda env list
          conda list

      - name: "Check model configuration"
        run: |
          conda activate speclet
          python3 speclet/cli/check_model_configuration.py
