#### ---- SpecletTwo ---- ####

- name: sp2-default
  description: Default SpecletTwo model.
  model: speclet-two
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true

#### ---- SpecletFour ---- ####

- name: sp4-default
  description: Default settings for SpecletFour.
  model: speclet-four
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

- name: sp4-default-fullrank
  description: Default settings for SpecletFour but fit with FullRank ADVI.
  model: speclet-four
  fit_methods:
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      ADVI:
        method: "fullrank_advi"

- name: sp4-noncentered
  description: SpecletFour with all covariates in non-centered parameterization.
  model: speclet-four
  config:
    h: noncentered
    d: noncentered
    η: noncentered
  fit_methods:
    - ADVI
    - MCMC
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

- name: sp4-noncentered-copynum
  description: SpecletFour with all covariates, including copy number, in non-centered parameterization.
  model: speclet-four
  config:
    copy_number_cov: true
    h: noncentered
    d: noncentered
    β: noncentered
    η: noncentered
  fit_methods:
    - ADVI
    - MCMC
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

- name: sp4-centered-copynum
  description: SpecletFour with all covariates, including copy number, in centered parameterization.
  model: speclet-four
  config:
    copy_number_cov: true
    h: centered
    d: centered
    β: centered
    η: centered
  fit_methods:
    - ADVI
    - MCMC
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

#### ---- SpecletFive ---- ####

- name: sp5-default
  description: Default settings for SpecletFive.
  model: speclet-five
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

- name: sp5-noncentered
  description: SpecletFive with all variables using the non-centered parameterization.
  model: speclet-five
  config:
    a: noncentered
    d: noncentered
    h: noncentered
    j: noncentered
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

#### ---- SpecletSix ---- ####

- name: sp6-default
  description: Default settings for SpecletSix.
  model: speclet-six
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95

#### ---- SpecletSeven ---- ####

- name: sp7-default
  description: Default settings for SpecletSeven.
  model: speclet-seven
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95
- name: sp7-advi-fullrank
  description: Default settings for SpecletSeven.
  model: speclet-seven
  fit_methods:
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      ADVI:
        method: "fullrank_advi"
- name: sp7-intercept-noncentered
  description: SpecletSeven with everything default except for a non-centered parameterization of μ_h.
  model: speclet-seven
  config:
    μ_h: noncentered
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95
- name: sp7-cellline-cn
  description: SpecletSeven with the cell line copy number covariate.
  model: speclet-seven
  config:
    cell_line_cna_cov: true
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95
- name: sp7-cellline-cn-ncp
  description: |
    SpecletSeven with the cell line copy number covariate with non-centered
    parameterizations for μ_k and μ_h.
  model: speclet-seven
  config:
    cell_line_cna_cov: true
    μ_k: noncentered
    μ_h: noncentered
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        target_accept: 0.95
