
# --- Hierarchical negative binomial model ---

- name: hnb-small-data
  description: "
    Fit the model with a relatively small amount of data for testing purposes.
  "
  active: true
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_PANC_ESO_SUBSAMPLE
  sampling_kwargs:
    pymc_mcmc:
      target_accept: 0.99
      init: "advi+adapt_diag"
    pymc_numpyro:
      target_accept: 0.99
  slurm_resources:
    PYMC_MCMC:
      mem: 32
      time: 8
      cores: 1
    PYMC_NUMPYRO:
      mem: 32
      time: 8
      cores: 1
