
# ---- Configuration specification ----

- name: example-specification          # UUID name of this model and configuration.
  description: An example config spec. # Some helpful description of the model.
  model: SIMPLE_NEGATIVE_BINOMIAL      # Model to fit.
  data_file: DEPMAP_CRC_BONE_SUBSAMPLE # Data file.
  sampling_kwargs:                     # Optional arguments to provide for posterior sampling methods.
    stan_mcmc:
      num_chains: 2
      num_samples: 1000
    pymc3_mcmc:
      draws: 1000
      init: "advi"
    pymc3_advi:
      n: 200000
  pipelines:                          # Which pipelines to include this model config in.
    fitting: [STAN_MCMC, PYMC3_MCMC, PYMC3_ADVI]
    sbc: [STAN_MCMC, PYMC3_MCMC, PYMC3_ADVI]


# ---- Negative binomial model ----

- name: simple-nb
  description: A simple negative binomial model.
  model: SIMPLE_NEGATIVE_BINOMIAL
  data_file: DEPMAP_CRC_BONE_SUBSAMPLE
  pipelines:
    fitting: [STAN_MCMC, PYMC3_MCMC]


# ---- Hierarchical negative binomial model ----

- name: hierarchical-nb
  description: A hierarchical negative binomial model.
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_SUBSAMPLE
  pipelines:
    fitting: [STAN_MCMC, PYMC3_MCMC]
