
# --- Hierarchical negative binomial model ---

- name: hnb-comutation-synlet
  description: "
    A hierarchical negative binomical generalized linear model with covariates for
    different molecular covariates and a covariate for co-mutation with known cancer-
    related genes. The cancer genes are from COSMIC's CGC and lineage-specific.
  "
  active: true
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_SUBSAMPLE
  sampling_kwargs:
    pymc_mcmc:
      target_accept: 0.99
      init: "adapt_diag"
    pymc_numpyro:
      target_accept: 0.99
  slurm_resources:
    PYMC_MCMC:
      mem: 32
      time: 8
      cores: 1
    PYMC_NUMPYRO:
      mem: 32
      time: 8
      cores: 1
