

# --- Test cases ---

- name: hnb-single-lineage-prostate-009
  description: "
    Single lineage hierarchical negative binomial model for prostate data from the
    Broad.
    Varying effects for each chromosome of each cell line has been nested under the
    existing varying effects for cell line.
  "
  active: true
  model: LINEAGE_HIERARCHICAL_NB
  data_file: "modeling_data/lineage-modeling-data/depmap-modeling-data_prostate.csv"
  model_kwargs:
    lineage: "prostate"
  sampling_kwargs:
    pymc_numpyro:
      draws: 1000
      tune: 2000
      target_accept: 0.98
      idata_kwargs:
        log_likelihood: false
      nuts_kwargs:
        step_size: 0.01
  slurm_resources:
    PYMC_NUMPYRO:
      mem: 16
      time: 8
      cores: 1
      gpu:
        gpu: "RTX 8000"


- name: hnb-single-lineage-colorectal-009
  description: "
    Single lineage hierarchical negative binomial model for colorectal data from the
    Broad.
    Varying effects for each chromosome of each cell line has been nested under the
    existing varying effects for cell line.
  "
  active: true
  model: LINEAGE_HIERARCHICAL_NB
  data_file: "modeling_data/lineage-modeling-data/depmap-modeling-data_colorectal.csv"
  model_kwargs:
    lineage: "colorectal"
    min_frac_cancer_genes: 0.2
  sampling_kwargs:
    pymc_numpyro:
      draws: 1000
      tune: 2000
      target_accept: 0.99
      idata_kwargs:
        log_likelihood: false
      nuts_kwargs:
        step_size: 0.01
  slurm_resources:
    PYMC_NUMPYRO:
      mem: 64
      time: 24
      cores: 1
      gpu:
        gpu: "RTX 8000"


- name: hnb-single-lineage-liver-009
  description: "
    Single lineage hierarchical negative binomial model for liver data from the
    Broad.
    Varying effects for each chromosome of each cell line has been nested under the
    existing varying effects for cell line.
  "
  active: false
  model: LINEAGE_HIERARCHICAL_NB
  data_file: "modeling_data/lineage-modeling-data/depmap-modeling-data_liver.csv"
  model_kwargs:
    lineage: "liver"
    min_frac_cancer_genes: 0.2
  sampling_kwargs:
    pymc_numpyro:
      draws: 1000
      tune: 2000
      target_accept: 0.98
      idata_kwargs:
        log_likelihood: false
      nuts_kwargs:
        step_size: 0.01
  slurm_resources:
    PYMC_NUMPYRO:
      mem: 32
      time: 8
      cores: 1
      gpu:
        gpu: "RTX 8000"



# --- All lineages ---
# Generated automatically with `./speclet/cli/gen_lineage_configs.py`.

## >>> AUTO GEN LINEAGES >>>


## <<<
