- name: sp4-default-config
  description: Default settings for SpecletFour
  model: speclet-four
  fit_methods:
    - MCMC
    - ADVI
  pipelines:
    - fitting
    - sbc
- name: sp4-noncentered
  description: SpecletFour with all covariates in non-centered parameterization.
  model: speclet-four
  fit_methods:
    - ADVI
  config:
    h: noncentered
    d: noncentered
    η: noncentered
  pipelines:
    - fitting
- name: sp4-noncentered-copynum
  description: SpecletFour with all covariates, including copy number, in non-centered parameterization.
  model: speclet-four
  fit_methods:
    - ADVI
  config:
    copy_number_cov: true
    h: noncentered
    d: noncentered
    β: noncentered
    η: noncentered
  pipelines:
    - fitting
