# ---- SpecletEight ----

- name: eight-default
  description: Default SpecletEight model.
  model: speclet-eight
  fit_methods: ["MCMC"]
  pipelines: ["fitting"]
  debug: true
  pipeline_sampling_parameters:
    fitting:
      MCMC:
        prior_pred_samples: null
        sample_kwargs:
          tune: 2000
          draws: 2000
          target_accept: 0.95
          init: "advi"
          n_init: 25000
