
# ---- Configuration specification ----

# - name: example-specification          # UUID name of this model and configuration.
#   description: An example config spec. # Some helpful description of the model.
  # active: true                         # Activate/deactivate a model config.
#   model: SIMPLE_NEGATIVE_BINOMIAL      # Model to fit.
#   data_file: DEPMAP_CRC_BONE_SUBSAMPLE # Data file.
#   sampling_kwargs:                     # Optional arguments to provide for posterior sampling methods.
#     stan_mcmc:
#       num_chains: 2
#       num_samples: 1000
#     pymc3_mcmc:
#       draws: 1000
#       init: "advi"
#     pymc3_advi:
#       n: 200000
#   pipelines:                          # Which pipelines to include this model config in.
#     fitting: [STAN_MCMC, PYMC_MCMC, PYMC_ADVI]
#     sbc: [STAN_MCMC, PYMC_MCMC, PYMC_ADVI]


# ---- Hierarchical negative binomial model ----

- name: hnb-comutation-synlet
  description: "
    A hierarchical negative binomical generalized linear model with covariates for
    different molecular covariates and a covariate for co-mutation with known cancer-
    related genes. The cancer genes are from COSMIC's CGC and lineage-specific.
  "
  active: true
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_PANC_CERVIX_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc_mcmc:
      target_accept: 0.95
      init: "adapt_diag"
  pipelines:
    fitting: [PYMC_MCMC]
