
# ---- Configuration specification ----

# - name: example-specification          # UUID name of this model and configuration.
#   description: An example config spec. # Some helpful description of the model.
  # active: true                         # Activate/deactivate a model config.
#   model: SIMPLE_NEGATIVE_BINOMIAL      # Model to fit.
#   data_file: DEPMAP_CRC_BONE_SUBSAMPLE # Data file.
#   sampling_kwargs:                     # Optional arguments to provide for posterior sampling methods.
#     stan_mcmc:
#       num_chains: 2
#       num_samples: 1000
#     pymc3_mcmc:
#       draws: 1000
#       init: "advi"
#     pymc3_advi:
#       n: 200000
#   pipelines:                          # Which pipelines to include this model config in.
#     fitting: [STAN_MCMC, PYMC_MCMC, PYMC_ADVI]
#     sbc: [STAN_MCMC, PYMC_MCMC, PYMC_ADVI]


# ---- Negative binomial model ----

- name: simple-nb
  description: A simple negative binomial model.
  active: false
  model: SIMPLE_NEGATIVE_BINOMIAL
  data_file: DEPMAP_CRC_BONE_SUBSAMPLE
  pipelines:
    fitting: [PYMC_MCMC, STAN_MCMC]


# ---- Hierarchical negative binomial model ----

- name: hierarchical-nb
  description: A hierarchical negative binomial model.
  active: false
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc3_mcmc:
      target_accept: 0.95
    stan_mcmc:
      delta: 0.95
      refresh: 5
  pipelines:
    fitting: [PYMC_MCMC, STAN_MCMC]

- name: hierarchical-nb-blaswarning
  active: false
  description: "
    A hierarchical negative binomial model run with the BLAS warning from theano.
  "
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc3_mcmc:
      target_accept: 0.95
  pipelines:
    fitting: [PYMC_MCMC]

- name: hierarchical-nb_advi-init
  active: false
  description: A hierarchical negative binomial model. Initialized using ADVI in PyMC3.
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc3_mcmc:
      target_accept: 0.95
      init: "advi"
      n_init: 50000
  pipelines:
    fitting: [PYMC_MCMC]

- name: hnb-copynum-rna-mut-covariates
  description: "
    A hierarchical negative binomial model with copy number, RNA expression, and
    mutation status covariates..
  "
  active: false
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_BONE_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc_mcmc:
      target_accept: 0.95
      init: "adapt_diag"
  pipelines:
    fitting: [PYMC_MCMC]

- name: hnb-comutation-synlet
  description: "
    A hierarchical negative binomical generalized linear model with covariates for
    different molecular covariates and a covariate for co-mutation with known cancer-
    related genes. The cancer genes are from COSMIC's CGC and lineage-specific.
  "
  active: true
  model: HIERARCHICAL_NB
  data_file: DEPMAP_CRC_PANC_CERVIX_LARGE_SUBSAMPLE
  sampling_kwargs:
    pymc_mcmc:
      target_accept: 0.95
      init: "adapt_diag"
  pipelines:
    fitting: [PYMC_MCMC]

# ---- 2-Tier hierarchical negative binomial model ----

# - name: hierarchical-nb-second-tier
#   description: A hierarchical negative binomial model with a second tier.
#   model: HIERARCHICAL_NB_SECONDTIER
#   data_file: DEPMAP_CRC_BONE_SUBSAMPLE
#   sampling_kwargs:
#     pymc3_mcmc:
#       target_accept: 0.9
#     stan_mcmc:
#       delta: 0.9
#       refresh: 1
#   pipelines:
#     fitting: [PYMC_MCMC, STAN_MCMC]
